#Время до того,
#как предмет просрочится.
#(Указывать в секундах)
time: 1209600

#Черный список предметов.
blocked-items:
  - DIAMOND
  - APPLE

#Внешний вид
#инвентаря
#аукциона.
items:

  #Описание
  #продаваемого
  #предмета.
  offer-lore:
    - ''
    - '&7Продавец: &e<owner>'
    - ''
    - '&7Цена продажи: &a<price>$'
    - '&7Цена за штуку: &a<single-price>$'
    - '&7Просрочится через: &e<time>'
    - ''
    - '&7&oНажмите ЛКМ, чтобы купить все.'
    - '&7&oНажмите ПКМ, чтобы 1 штуку.'
    - ''

  #Описание
  #продаваемого
  #предмета во
  #вкладке со
  #своими
  #предметами.
  my-offer-lore:
    - ''
    - '&7Цена продажи: &a<price>$'
    - '&7Цена за штуку: &a<single-price>$'
    - '&7Просрочится через: &e<time>'
    - ''
    - '&7&oНажмите ЛКМ, чтобы снять с продажи.'
    - ''

  #Описание
  #просроченного
  #продаваемого
  #предмета во
  #вкладке со
  #своими
  #предметами.
  my-expired-offer-lore:
    - ''
    - '&7Цена продажи: &a<price>$'
    - '&7Цена за штуку: &a<single-price>$'
    - '&7Предмет &cпросрочился.'
    - ''
    - '&7&oНажмите ЛКМ, чтобы снять с продажи.'
    - ''

  #Стеклянная
  #панель.
  decor:

    #Тип предмета, его материал.
    #Поддерживаются "под-айди".
    type: 'STAINED_GLASS_PANE:7'

    #Отображаемое имя предмета.
    name: '&7'

    #Отображаемое описание предмета.
    lore: []

  #Предмет для
  #возвращения в
  #меню аукциона.
  back:

    type: COMPASS
    name: '&eВернуться'
    lore: []

  #Обновление
  #аукциона.
  reflesh:

    type: EMERALD
    name: '&eОбновить страницу'
    lore: []

  #Предмет
  #информации.
  info:

    type: SIGN
    name: '&eСправка'
    lore:
      - '&7На аукционе вы можете выставить свои предметы на продажу.'
      - '&7Для этого используйте &e/ah sell <цена> [количество]'
      - '&7и ждите, пока кто-нибудь купит ваш предмет. Если не указать'
      - '&7количество, то вы продадите сразу &eВСЕ&7 предметы в слоте.'

  #Предмет
  #свои продаж.
  my-offers:

    type: CHEST
    name: '&eМои предметы'
    lore:
      - '&7Здесь находятся предметы, которые вы продаете,'
      - '&7а также те, которые слишком долго находятся на'
      - '&7аукционе и, тем самым, просрочились.'

  #Предмет
  #сортировки.
  sort:

    type: PAPER
    name: '&eСортировка'
    lore:
      - '&7Данный предмет изменяет сортировку предметов.'
      - '&7Сейчас предмет отсортированы по &c<type>&7.'

  #Предмет для
  #перехода на
  #предыдущую
  #страницу.
  arrow-back:

    type: SPECTRAL_ARROW
    name: '&eПредыдущая страница'
    lore: []

  #Предмет для
  #перехода на
  #следующую
  #страницу.
  arrow-next:

    type: SPECTRAL_ARROW
    name: '&eСледующая страница'
    lore: []

  #Предмет
  #подтверждения.
  confirm:

    type: 'WOOL:5'
    name: '&aНажмите еще раз, чтобы подтвердить покупку.'
    lore: []

  #Если у игрока
  #не хватает денег.
  low-money:

    type: 'WOOL:14'
    name: '&cУ вас недостаточно денег для покупки.'
    lore: []

  #Если предмет
  #уже купили.
  purchased:

    type: 'WOOL:14'
    name: '&cДанный предмет уже был куплен, страница будет перезагружена.'
    lore: []

#Сообщения.
messages:

  #Помощь по командам.
  help: |-
    &r &r
    &r &e/ah help &7- помощь по командам.
    &r &e/ah sell <цена> [количество] &7- выставить предмет на аукцион.
    &r &r

  #Игрок выставил предмет на аукцион.
  put: '&7Вы выставили предмет на аукцион.'
  #У игрока купили предмет.
  sell: '&7Игрок &e<player> &7купил у вас &e<item> &7за &a<price>&7.'
  #Игрок купил предмет.
  buy: '&7Вы купили &e<item> &7за &a<price>&7.'
  #Игрок попытался выставить запрещенный предмет на аукцион.
  block: '&cДанный предмет запрещен для продажи на аукционе.'
  #Игрок попытался выставить на аукцион предмет, но у него уже максимум.
  max: '&cВы достигли максимума по количеству предметов на аукционе.'
  #У игрока недостаточно предметов для продажи.
  low: '&cУ вас недостаточно предметов для продажи.'